"""valid_answers_points

Revision ID: 55914db90ff6
Revises: 144eaccb9211
Create Date: 2024-09-30 12:35:14.124386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55914db90ff6'
down_revision: Union[str, None] = '144eaccb9211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'points')
    # ### end Alembic commands ###
