"""user is_blocked

Revision ID: e7e93dfb8887
Revises: 611b08ad57aa
Create Date: 2024-07-04 16:35:24.818976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e93dfb8887'
down_revision: Union[str, None] = '611b08ad57aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_blocked')
    # ### end Alembic commands ###
